export const PRONOUN_DUMBY_LIST = ['He/Him/His', 'She/Her/Hers', 'They/Them/Theirs'];
export const GENDER_DUMBY_LIST = ["Male", "Female", "Non-Binary", "Gender Queer"];
export const SPECS_DUMBY_LIST = [
    "Abuse",
    "Accessibility Concerns",
    "Addiction",
    "ADHD",
    "Anger/Anger Management",
    "Anti-Oppression Grief",
    "Anxiety",
    "ASD",
    "Attachment Disorder",
    "Behavioural Issues",
    "BIPOC",
    "Bipolar Disorder",
    "Body Image Challenges",
    "Borderline Personality Disorder",
    "Boundaries",
    "Burnout",
    "Capacity Building",
    "Career Development or Direction",
    "Career Issues",
    "Childhood Abuse/Neglect",
    "Childhood Trauma",
    "Codependency",
    "Communication Issues",
    "Couples",
    "Cross-Cultural Consideration in Clinical Practice",
    "Cultural Transitions",
    "Custom Group Workshops for Organizations",
    "Depression",
    "Developing Positive Habits",
    "Developmental Disabilities",
    "Developmental Disorders",
    "Dissociative Identity Disorder (DID)",
    "Domestic Violence",
    "Early Adulthood",
    "Eating Disorders",
    "Educational Psychology",
    "Emotional Disturbance",
    "Emotional Regulation/Resiliency",
    "Empowerment",
    "Existential Concern/Life Crises",
    "Family Conflict",
    "Family Dynamics/Conflict",
    "Goal Attainment",
    "Grief",
    "Grief/Loss",
    "Health",
    "Health Care Professionals",
    "High IQ",
    "Homesickness",
    "Identity Issues",
    "Immigrant Experiences",
    "Impulse Control Disorders",
    "Infidelity",
    "Intergenerational Trauma",
    "LGBTQIA+",
    "Life Changes",
    "Life Coaching",
    "Life Transitions",
    "Loneliness",
    "Low Motivation",
    "Marginalization",
    "Marital and Premarital",
    "Medical Students",
    "Men’s Issues",
    "Mixed-Race",
    "Mood Disorders",
    "Multicultural Counselling",
    "Negative Thinking Patterns",
    "Neurodivergence",
    "New Immigrant",
    "Non-Binary",
    "Nursing Students",
    "Obsessive-Compulsive Disorder (OCD)",
    "Oppositional Defiance",
    "Oppression",
    "Panic Disorder",
    "Parent-Child Relationship",
    "Parenting",
    "Peer Relationships",
    "Perfectionism",
    "Personal Growth/Development",
    "Personality Disorders",
    "Post-Traumatic Stress Disorder (PTSD)",
    "Pregnant and/or Postpartum Parents",
    "Queer Issues",
    "Racial Identity",
    "Relationship Issues",
    "Self-Harming",
    "Self Esteem",
    "Separation",
    "Sexual Abuse",
    "Sexuality",
    "Spirituality",
    "Stress Management/Stress",
    "Students",
    "Substance Use",
    "Suicidal Ideation",
    "Teen Violence",
    "Trans",
    "Trauma",
    "Trauma and PTSD",
    "Women’s Issues",
    "Youth/Young Adults",
];
export const CREDS_DUMBY_LIST = [
    'PhD',
    'MSW',
    'MA',
    'M.Ed',
    'MC',
    'M.Sc',
    'BA',
    'BSc',
    'BSW',
    'R.Psych',
    'RSW',
    'RCSW',
    'RCC',
    'CCC',
    'RPC',
    'RMFT',
];
export const LANG_DUMBY_LIST = [
    "Bosnian",
    "Cantonese",
    "Croatian",
    "English",
    "Farsi",
    "French",
    "Greek",
    "Hindu",
    "Korean",
    "Mandarin",
    "Punjabi",
    "Serbian",
    "Spanish",
    "German",
    "Swedish",
    "Italian",
    "Danish",
];
export const APPROACH_DUMBY_LIST = [
    "Accelerated Experiential-Dynamic Psychotherapy",
    "Acceptance and Commitment (ACT)",
    "AEDP",
    "Applied Behavioural Analysis",
    "Art Therapy",
    "Attachment-Based",
    "Brief Therapy",
    "Clinical Supervision and Licensed Supervisors",
    "Cognitive Behavioural Therapy (CBT)",
    "Compassion Focused",
    "Culturally Sensitive",
    "Dialectical Behavioural Therapy (DBT)",
    "Eclectic",
    "Eclectic (Trauma-Informed)",
    "EMDR",
    "Emotion-Focused Therapy",
    "Emotionally Focused",
    "Energy Psychology",
    "Evidence Based",
    "Existentialism",
    "Experiential Therapy",
    "Expressive Arts",
    "Family Systems",
    "Feminist Therapy",
    "Focusing",
    "Focusing-Oriented Therapy",
    "Gestalt",
    "Holistic Psychology",
    "Humanistic",
    "Imago",
    "Integrative",
    "Internal Family Systems (IFS)",
    "Interpersonal",
    "Intervention",
    "Life Coach/Coaching",
    "Mindfulness-Based (MBCT)",
    "Mindfulness and Meditation",
    "Motivational Interviewing",
    "Multi-Dimensional",
    "Multicultural",
    "Narrative Therapy",
    "Nature Therapy",
    "Parent-Child Interaction (PCIT) Sandplay",
    "Person-Centered",
    "Play Therapy",
    "Positive Psychology",
    "Reality Therapy",
    "Schema Therapy",
    "Self-Compassion",
    "Self Relational Theory and Therapy",
    "Sensorimotor Psychotherapy (SP)",
    "Solution-Focused Therapy",
    "Somatic",
    "Strength-Based",
    "Trauma-Focused",
    "Trauma-Focused Compassionate Inquiry",
    "Trauma-Informed",
];